### ISSUE TITLE
Installation process for experiments

### ISSUE THREAD

**Issue by Jasstkn** [litmuschaos/chaos-charts#220]
Hello,
how do you feel about making installation process for experiments in this repo more helm native?
Like, helm install --version <version> chart-name and etc.? 

I would like to install charts using declarative approach (helmfile tool), but it's strange to me using some bash commands without actually using helm :)

**Comment by ksatchit** [comment]
A repo was actually created for the purpose suggested: https://github.com/litmuschaos/chaos-helm
(provides generic experiments chart)

This repo serves as a canonical representation/backend for the hub. For example, this custom file (called chartServiceVersion) https://github.com/litmuschaos/chaos-charts/blob/master/charts/generic/generic.chartserviceversion.yaml is what is rendered as:

- This card on the hub. 

![image](https://user-images.githubusercontent.com/21166217/80359599-a94e2280-889b-11ea-900d-14e6b4d3dcbd.png)

- This "generic" chart page: 

![image](https://user-images.githubusercontent.com/21166217/80359700-d69ad080-889b-11ea-9152-27324318b15a.png)

**Comment by Jasstkn** [comment]
But there is no charts, it's confusing. 😢

**Comment by ksatchit** [comment]
Ok the "chart" term in **this** repo denotes a different purposes :-) -- it refers to a "category" or "bundle" of chaos experiments that are created against a platform/app. 

For **helm chart** installation refer: https://github.com/litmuschaos/chaos-helm/blob/master/README.md

**Comment by Jasstkn** [comment]
Hm, I'm afraid that after installation there isn't any experiments. 
Also, there is a mistake in description (https://github.com/litmuschaos/chaos-helm/blob/master/README.md#chaos-helm), because that chart doesn't support administatorMode yet. (I'm preparing PR for it)

**Comment by Jasstkn** [comment]
closed
