### ISSUE TITLE
Tested AKS

### ISSUE THREAD

**Issue by torumakabe** [litmuschaos/chaos-charts#247]
I tested some generic experiments on Azure Kubernetes Service. It worked well. Are there any processes or guidelines to add AKS to tested platforms? Thanks in advance.

**Comment by ksatchit** [comment]
Thanks much @ToruMakabe for testing out the experiments on AKS!! Really appreciate! 

Re: the process to be followed: 

- Changes in Litmus Documentation: 

   -  (_if applicable_) As you may have noticed, the [experiment docs](https://docs.litmuschaos.io/docs/pod-delete/) have a pre-requisites/details/other sections which help users to prepare for the experiment. If there are any instructions specific to AKS that you would like to let users know, it would be good to add them into these sections.  

   - (_necessary_) Of course, adding AKS to the "Tested K8s Platforms column" in respective experiment docs. 

      The source is here: https://github.com/litmuschaos/litmus-docs/tree/master/docs/  in (*experiment-name*.md)

   - (_if applicable_) On similar lines, if there are any specific guidelines you needed to follow or some gotchas you experienced wrt the litmus infra - i.e., in running the operator/installing CRDs etc., and you feel it derserves mention, you could create a separate section for AKS here in the [platforms](https://docs.litmuschaos.io/docs/openshift-litmus/) section. A new doc can be added for AKS and added into the [sidebar](https://github.com/litmuschaos/litmus-docs/blob/master/website/sidebars.json#L22)

- Changes on the chaos-charts (this) repo: 

  - This repo is the canonical source for the [chaoshub](https://hub.litmuschaos.io/generic/pod-delete), where manifests called [<prefix>_chartserviceversion.yaml](https://github.com/litmuschaos/chaos-charts/blob/master/charts/generic/pod-delete/pod-delete.chartserviceversion.yaml#L21) holds info rendered on the hub pages -- which is one more place where we display supported platforms. 

   - (_necessary_) Please add AKS to the supported platform list in the experiments you used. 

Eventually this should lead us to add the AKS as an CI/e2e platform depending upon resources available!

**Comment by torumakabe** [comment]
@ksatchit Thanks! I will follow the process.

**Comment by ksatchit** [comment]
Hey @ToruMakabe ! Was just wondering, if you would like to add yourself as an adopter of litmus if you are using it in any way -test/dev/staging & share your usecase briefly here: https://github.com/litmuschaos/litmus/blob/master/ADOPTERS.md

You can join our slack channel for more discussions around experiments & chaos in general: https://app.slack.com/client/T09NY5SBT/CNXNB0ZTN

Also, would be awesome to hear more from you on what you like about litmus/what improvements you would like to see being made & any other feedback you might have. Thank you!
