### ISSUE TITLE
Broken sample Chaos Engine (node-memory-hog)

### ISSUE THREAD

**Issue by torumakabe** [litmuschaos/chaos-charts#270]
node-memory-hog sample Chaos Engine (v1.6.0) seems [broken](https://hub.litmuschaos.io/api/chaos/1.6.0?file=charts/generic/node-memory-hog/engine.yaml). There are some unneeded word "(MISSING)". 

Could you please check it? Thanks!

**Comment by ksatchit** [comment]
Indeed it is broken :(  Thanks for bringing this to notice! Fix underway.

**Comment by ksatchit** [comment]
Just learning that the [CR](https://github.com/litmuschaos/chaos-charts/blob/master/charts/generic/node-memory-hog/engine.yaml) within this repo is fine, but an issue creeps in while rendering on the hub: This needs to be fixed.
