### ISSUE TITLE
Can't pull image "litmuschaos/ansible-runner:1.13.0" for litmus test-case coreDNS-pod-delete

### ISSUE THREAD

**Issue by digvijay2040** [litmuschaos/chaos-charts#454]
Can't find image litmuschaos/ansible-runner:1.13.0 in dockerhub due to which we are getting
Back-off pulling image "litmuschaos/ansible-runner:1.13.0"
Error: ImagePullBackOff

docker pull litmuschaos/ansible-runner:1.13.0
Error response from daemon: manifest for litmuschaos/ansible-runner:1.13.0 not found: manifest unknown: manifest unknown

Image is used in : https://github.com/litmuschaos/chaos-charts/blob/f60c99bfa3416eaf77ce7b562a3c047d51489612/charts/coredns/coredns-pod-delete/experiment.yaml#L36

**Comment by uditgaurav** [comment]
Hi @digvijay2040 you can use `litmuschaos/ansible-runner:1.13.5` which is latest as of now.

**Comment by uditgaurav** [comment]
Closing the issue. Feel free to reopen it if you face any issue regarding this.
