### ISSUE TITLE
AWS Auth Failure 

### ISSUE THREAD

**Issue by TajaneSwapnil** [litmuschaos/chaos-charts#476]
I'm trying to execute ec2-terminate-by-id experiment.

I have followed all the steps in the document and executed the experiment

I got following error after execution.
`time="2021-06-23T02:15:12Z" level=error msg="failed to get the ec2 instance status, err: AuthFailure: AWS was not able to validate the provided access credentials\n\tstatus code: 401, request id: 92cc03a9-7fc3-4011-a511-844a10f66a7b"`

I have verified that /tmp/cloud_config file is present and have valid access credentials.

I would like to know what else I can look for to resolve this issue

Thank you

**Comment by TajaneSwapnil** [comment]
Complete log is as below
`[root@ip-172-16-0-198 ~]# kubectl logs -f ec2-terminate-by-id-a8jff1-gqjjx
W0623 02:15:12.473572       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-06-23T02:15:12Z" level=info msg="Experiment Name: ec2-terminate-by-id"
time="2021-06-23T02:15:12Z" level=info msg="[PreReq]: Getting the ENV for the  experiment"
time="2021-06-23T02:15:12Z" level=info msg="[PreReq]: Updating the chaos result of ec2-terminate-by-id experiment (SOT)"
time="2021-06-23T02:15:12Z" level=info msg="The instance information is as follows" Chaos Namespace=default Ramp Time=0 Instance ID=i-0b2da976dc0cc4f6f Sequence=parallel Chaos Duration=30
time="2021-06-23T02:15:12Z" level=info msg="The Node status are as follows" Node=ip-192-168-23-196.ap-northeast-1.compute.internal Ready=true
time="2021-06-23T02:15:12Z" level=info msg="The Node status are as follows" Node=ip-192-168-5-235.ap-northeast-1.compute.internal Ready=true
time="2021-06-23T02:15:12Z" level=info msg="The Node status are as follows" Node=ip-192-168-51-154.ap-northeast-1.compute.internal Ready=true
time="2021-06-23T02:15:12Z" level=info msg="The Node status are as follows" Ready=true Node=ip-192-168-72-110.ap-northeast-1.compute.internal
time="2021-06-23T02:15:12Z" level=info msg="[Info]: Total number active nodes are: 4"
time="2021-06-23T02:15:12Z" level=info msg="[Status]: Verify that the AUT (Application Under Test) is running (pre-chaos)"
time="2021-06-23T02:15:12Z" level=info msg="[Status]: No appLabels provided, skipping the application status checks"
time="2021-06-23T02:15:12Z" level=info msg="[Info]: The instances under chaos(IUC) are: [i-0b2da976dc0cc4f6f]"
time="2021-06-23T02:15:12Z" level=error msg="failed to get the ec2 instance status, err: AuthFailure: AWS was not able to validate the provided access credentials\n\tstatus code: 401, request id: 92cc03a9-7fc3-4011-a511-844a10f66a7b"`

**Comment by prithvi1307** [comment]
@uditgaurav PTAL

**Comment by TajaneSwapnil** [comment]
Resolved by regenerating the access keys from AWS Console
